Add policy create, rm, ls to admin cli
Put utility functions common to vmdk_ops, vmdkops_admin and vsan_policy in
vmdk_utils.py

Add policy and size validation to vmdk_ops.createVMDK

Return error on createVMDK if the format for size is incorrect or the policy
doesn't exist

Cleanup some buggy code and formatting in createVMDK

Check if policy already exists before creating

Don't allow removal of a policy if it's in use

Note that while the policies are created and populated in KV they are not
actually configured on the VMDKs because no VSAN specific code is in this PR.
Also note that we pretend the first datastore in the list of datastores is the
VSAN datastore for now.

vmdkops_admin.py ls -l has been modified to show the policy name in use by the
volume, or [VSAN default] if no policy is in use. This however assumes that all
volumes are VSAN volumes. In a future commmit we will need to change this to
show 'N/A' for non-vsan volumes. We'll also need to distinguish vsan from
non-vsan volumes when listing policies with `policy ls`.

`policy update` will be added in a future PR as it is heavily depended on
objtool wrapping code being added in another PR.

Below are some interactive sessions showing the usage of the code in this PR:

 ### Try to create a volume with an option that doesn't exist
```
ajs@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ docker
volume create --driver vmdk --name failme -o policy=blah
Error response from daemon: create failme: VolumeDriver.Create: Invalid options: [u'policy']
```

 ### Try to create a volume with a policy that doesn't exist
```
ajs@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ docker
volume create --driver vmdk --name failme -o vsan-policy-name=blah
Error response from daemon: create failme: VolumeDriver.Create: Policy blah does not exist
```

 ### Create a policy from the admin CLI
```
root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy create --name new_policy --content some_content
Successfully created policy: new_policy
```

 ### Create a volume that uses that policy
Note that this policy is not a real policy and we aren't actually using it yet.
However, it does get
stored in KV.

```
js@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ docker volume create --driver vmdk --name some_volume -o vsan-policy-name=new_policy
some_volume
```

 ### List all volumes and their policies from the CLI
Note that `yo` and `yo2` were previously existing volumes with no policy
```
[root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy ls
[root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy ls
Policy Name  Policy Content  Active
-----------  --------------  ------
new_policy   some-content    Unused
```

 ### Try to remove a policy from the admin CLI and fail because it's in use
```
[root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy rm
new_policy
Error: Cannnot remove. Policy in use by some_volume.vmdk
```

 ### Remove the volume using new_policy
```
ajs@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ docker volume rm some_volume
some_volume
ajs@ajs-virtual-machine:~/go/src/github.com/vmware/docker-volume-vsphere$ docker volume ls
DRIVER              VOLUME NAME
vmdk                yo2
vmdk                yo
```

 ### List volumes and their policies showing unused policies
```
[root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy ls
Volume    Policy Name     Policy Content
--------  --------------  --------------
yo2.vmdk  [VSAN default]  N/A
yo.vmdk   [VSAN default]  N/A
[UNUSED]  new_policy      some_content
```

 ### Remove new_policy now that it isn't in use
```
[root@localhost:/usr/lib/vmware/vmdkops/bin] ./vmdkops_admin.py policy rm new_policy
Successfully removed policy: new_policy
```

Address review comments

Fix after rebase

Strip whitespace off policy content when listing

Use a list for opts to fix sort issue